spring.application.name=codingacademy
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/codingacademy
spring.datasource.username=root
spring.datasource.password=Ud@y7610
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_TJPjlPz65ZK8HV
razorpay.key.secret=3VhWEBMPQkYa1MO0rUFj4RsZ